language: java
env: 
  global: 
    secure: mW12MspPr9MbSeNiUan2lLWSWucm/ClCusuh+lthviXrW/E3y5qluogV+SFumSCrn4PX+9gjOnQdbUfLFbDboHNhk/VO0ah1/OktumIyQpkORisyWyuf4e13LFYUWZ1GCei7azcRT0nDcG8qiEu3RB+zAzOHDaK3lZJ36DEUDuA=
before_install: echo $TRAVIS_SECURE_ENV_VARS
notifications: 
  email: false
script: mvn clean deploy
